apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==  # base64 for 'root'
  mongo-root-password: cGFzc3dvcmQ=  # base64 for 'password'
